--- # Ansible conditional example
- hosts: remote
  vars:
    target_file: /home/ansible/hostname
  tasks:
    - name: gather file information
      stat:
        path: "{{ target_file }}"
      register: hostname
    - name: Rename hostname when found
      command: mv "{{ target_file }}" /home/ansible/net-info
      when: hostname.stat.exists
