--- # Delegation Example
- hosts: centos
  tasks:
    - name: Run sleep.sh
      command: /home/ansible/sleep.sh
      async: 60
      poll: 0
      delegate_to: f80b2797831c.mylabserver.com
    - name: Install mariadb
      package:
        name: mariadb
        state: latest
      become: yes

